import { icd9cmEklaimProcedures } from "@/lib/icd-procedures-eklaim"

/**
 * Data ICD-10 (Diagnosa) dan ICD-9-CM (Tindakan Medis) untuk keperluan Asesmen klinis.
 * Daftar ini berisi kode dan nama yang umum digunakan di fasilitas kesehatan Indonesia.
 */

export type IcdDiagnosisItem = {
  code: string
  name: string
}

export type IcdProcedureItem = {
  code: string
  name: string
}

/** Daftar diagnosa ICD-10 umum */
export const icdDiagnoses: IcdDiagnosisItem[] = [
  // A — Infeksi tertentu
  { code: "A01.0", name: "Demam tifoid" },
  { code: "A09",   name: "Diare dan gastroenteritis infeksi" },
  { code: "A15.9", name: "Tuberkulosis pernapasan, tidak spesifik" },
  { code: "A16.2", name: "Tuberkulosis paru tanpa konfirmasi bakteriologis" },
  { code: "A46",   name: "Erisipelas" },
  { code: "A49.0", name: "Infeksi stafilokokal, tidak spesifik" },
  { code: "A49.1", name: "Infeksi streptokokal, tidak spesifik" },
  { code: "A60.0", name: "Infeksi herpes simpleks genital dan urogenital" },
  { code: "A63.0", name: "Kondiloma akuminata" },
  { code: "A90",   name: "Demam dengue [dengue klasik]" },
  { code: "A91",   name: "Demam berdarah dengue" },
  { code: "A97.0", name: "Demam dengue tanpa tanda bahaya" },
  { code: "A97.1", name: "Demam dengue dengan tanda bahaya" },
  { code: "A97.2", name: "Demam dengue berat" },

  // B — Penyakit virus dan parasit
  { code: "B00.1", name: "Gingivostomatitis dan faringotonsilitis herpetik" },
  { code: "B01.9", name: "Varisela tanpa komplikasi" },
  { code: "B02.9", name: "Herpes zoster tanpa komplikasi" },
  { code: "B05.9", name: "Morbili (campak) tanpa komplikasi" },
  { code: "B06.9", name: "Rubela tanpa komplikasi" },
  { code: "B15.9", name: "Hepatitis A akut tanpa koma hepatik" },
  { code: "B16.9", name: "Hepatitis B akut tanpa delta-agen dan tanpa koma hepatik" },
  { code: "B17.1", name: "Hepatitis C akut" },
  { code: "B18.1", name: "Hepatitis B kronis tanpa delta-agen" },
  { code: "B18.2", name: "Hepatitis C kronis" },
  { code: "B20",   name: "Penyakit oleh HIV yang mengakibatkan penyakit infeksi dan parasit" },
  { code: "B24",   name: "Penyakit oleh HIV, tidak spesifik" },
  { code: "B34.9", name: "Infeksi virus, tidak spesifik" },
  { code: "B35.4", name: "Tinea corporis" },
  { code: "B35.6", name: "Tinea pedis" },
  { code: "B37.0", name: "Kandidiasis mukosa mulut (oral thrush)" },
  { code: "B37.3", name: "Kandidiasis vulvovaginal" },
  { code: "B50.0", name: "Malaria falciparum dengan komplikasi serebral" },
  { code: "B54",   name: "Malaria, tidak spesifik" },
  { code: "B77.0", name: "Askariasis dengan komplikasi usus" },
  { code: "B86",   name: "Skabies" },

  // D — Darah
  { code: "D50.9", name: "Anemia defisiensi besi, tidak spesifik" },
  { code: "D51.0", name: "Anemia defisiensi vitamin B12" },
  { code: "D64.9", name: "Anemia, tidak spesifik" },
  { code: "D69.3", name: "Purpura trombositopenik idiopatik" },

  // E — Endokrin dan metabolisme
  { code: "E03.9", name: "Hipotiroidisme, tidak spesifik" },
  { code: "E05.0", name: "Tirotoksikosis dengan gondok difus" },
  { code: "E05.9", name: "Tirotoksikosis, tidak spesifik" },
  { code: "E10.9", name: "Diabetes melitus tipe 1 tanpa komplikasi" },
  { code: "E11.0", name: "Diabetes melitus tipe 2 dengan koma" },
  { code: "E11.9", name: "Diabetes melitus tipe 2 tanpa komplikasi" },
  { code: "E11.40", name: "Diabetes melitus tipe 2 dengan neuropati diabetik" },
  { code: "E11.51", name: "Diabetes melitus tipe 2 dengan retinopati nonproliferatif" },
  { code: "E11.65", name: "Diabetes melitus tipe 2 dengan hiperglikemia" },
  { code: "E14.9", name: "Diabetes melitus tidak spesifik, tanpa komplikasi" },
  { code: "E66.0", name: "Obesitas akibat asupan kalori berlebih" },
  { code: "E78.0", name: "Hiperkolesterolemia murni" },
  { code: "E78.5", name: "Hiperlipidemia, tidak spesifik" },
  { code: "E87.6", name: "Hipokalemia" },

  // F — Jiwa
  { code: "F20.9", name: "Skizofrenia, tidak spesifik" },
  { code: "F31.9", name: "Gangguan afektif bipolar, tidak spesifik" },
  { code: "F32.1", name: "Episode depresi sedang" },
  { code: "F32.9", name: "Episode depresif, tidak spesifik" },
  { code: "F41.0", name: "Gangguan panik" },
  { code: "F41.1", name: "Gangguan ansietas menyeluruh" },
  { code: "F43.1", name: "Gangguan stres pascatrauma (PTSD)" },
  { code: "F51.0", name: "Insomnia nonorganik" },

  // G — Saraf
  { code: "G20",   name: "Penyakit Parkinson" },
  { code: "G30.9", name: "Penyakit Alzheimer, tidak spesifik" },
  { code: "G35",   name: "Sklerosis multipel" },
  { code: "G40.9", name: "Epilepsi, tidak spesifik" },
  { code: "G43.9", name: "Migrain, tidak spesifik" },
  { code: "G44.2", name: "Sakit kepala tipe tegang" },
  { code: "G45.9", name: "Serangan iskemik transient (TIA), tidak spesifik" },
  { code: "G47.0", name: "Insomnia" },
  { code: "G47.3", name: "Apnea tidur" },
  { code: "G51.0", name: "Palsi Bell" },
  { code: "G54.2", name: "Gangguan akar saraf servikal" },
  { code: "G62.9", name: "Polineuropati, tidak spesifik" },

  // H — Mata dan telinga
  { code: "H10.9", name: "Konjungtivitis, tidak spesifik" },
  { code: "H25.9", name: "Katarak senilis, tidak spesifik" },
  { code: "H40.1", name: "Glaukoma sudut terbuka primer" },
  { code: "H61.2", name: "Serumen terimpak" },
  { code: "H65.9", name: "Otitis media nonsupuratif, tidak spesifik" },
  { code: "H66.0", name: "Otitis media supuratif akut (OMSA)" },
  { code: "H66.4", name: "Otitis media supuratif, tidak spesifik" },
  { code: "H81.0", name: "Penyakit Ménière" },
  { code: "H81.3", name: "Vertigo perifer lainnya" },

  // I — Sirkulasi
  { code: "I10",   name: "Hipertensi esensial (primer)" },
  { code: "I11.0", name: "Penyakit jantung hipertensif dengan gagal jantung" },
  { code: "I20.0", name: "Angina pektoris tidak stabil" },
  { code: "I20.9", name: "Angina pektoris, tidak spesifik" },
  { code: "I21.0", name: "Infark miokard akut transmural anterior" },
  { code: "I21.9", name: "Infark miokard akut, tidak spesifik (STEMI)" },
  { code: "I25.1", name: "Penyakit jantung aterosklerotik" },
  { code: "I26.9", name: "Emboli paru tanpa mention jantung pulmoner akut" },
  { code: "I48.0", name: "Fibrilasi atrial paroksismal" },
  { code: "I48.2", name: "Fibrilasi atrial kronis" },
  { code: "I50.0", name: "Gagal jantung kongestif (CHF)" },
  { code: "I50.9", name: "Gagal jantung, tidak spesifik" },
  { code: "I60.9", name: "Perdarahan subaraknoid, tidak spesifik" },
  { code: "I61.9", name: "Perdarahan intraserebral, tidak spesifik" },
  { code: "I63.9", name: "Infark serebral, tidak spesifik" },
  { code: "I64",   name: "Stroke, tidak disebutkan sebagai perdarahan atau infark" },
  { code: "I73.9", name: "Penyakit vaskular perifer, tidak spesifik" },
  { code: "I83.9", name: "Varises vena ekstremitas bawah tanpa ulkus atau radang" },

  // J — Pernapasan
  { code: "J00",   name: "Nasofaringitis akut (pilek / common cold)" },
  { code: "J01.0", name: "Sinusitis maksilaris akut" },
  { code: "J01.9", name: "Sinusitis akut, tidak spesifik" },
  { code: "J02.0", name: "Faringitis streptokokal" },
  { code: "J02.9", name: "Faringitis akut, tidak spesifik" },
  { code: "J03.0", name: "Tonsilitis streptokokal" },
  { code: "J03.9", name: "Tonsilitis akut, tidak spesifik" },
  { code: "J04.0", name: "Laringitis akut" },
  { code: "J06.9", name: "Infeksi saluran napas atas akut, tidak spesifik (ISPA)" },
  { code: "J11.1", name: "Influenza dengan manifestasi pernapasan lain" },
  { code: "J18.0", name: "Pneumonia bronkial, tidak spesifik" },
  { code: "J18.9", name: "Pneumonia, tidak spesifik" },
  { code: "J20.9", name: "Bronkitis akut, tidak spesifik" },
  { code: "J30.1", name: "Rinitis alergik akibat serbuk sari" },
  { code: "J30.4", name: "Rinitis alergik, tidak spesifik" },
  { code: "J32.9", name: "Sinusitis kronis, tidak spesifik" },
  { code: "J35.0", name: "Tonsilitis kronis" },
  { code: "J35.3", name: "Hipertrofi tonsil dengan hipertrofi adenoid" },
  { code: "J40",   name: "Bronkitis, tidak disebutkan sebagai akut atau kronis" },
  { code: "J44.1", name: "Penyakit paru obstruktif kronik dengan eksaserbasi akut (PPOK)" },
  { code: "J45.0", name: "Asma predominan alergik" },
  { code: "J45.9", name: "Asma, tidak spesifik" },

  // K — Pencernaan
  { code: "K21.0", name: "GERD dengan esofagitis" },
  { code: "K21.9", name: "Penyakit refluks gastroesofagus tanpa esofagitis (GERD)" },
  { code: "K25.9", name: "Tukak lambung, tidak spesifik" },
  { code: "K26.9", name: "Tukak duodenum, tidak spesifik" },
  { code: "K29.7", name: "Gastritis, tidak spesifik" },
  { code: "K30",   name: "Dispepsia fungsional" },
  { code: "K35.2", name: "Apendisitis akut dengan peritonitis difus" },
  { code: "K37",   name: "Apendisitis, tidak spesifik" },
  { code: "K40.9", name: "Hernia inguinalis unilateral tanpa obstruksi atau gangren" },
  { code: "K42.9", name: "Hernia umbilikalis tanpa obstruksi atau gangren" },
  { code: "K59.0", name: "Konstipasi" },
  { code: "K59.1", name: "Diare fungsional" },
  { code: "K72.9", name: "Gagal hati, tidak spesifik" },
  { code: "K74.6", name: "Sirosis hati lainnya dan tidak spesifik" },
  { code: "K76.0", name: "Perlemakan hati, tidak terklasifikasi (NAFLD)" },
  { code: "K80.2", name: "Batu kandung empedu tanpa kolesistitis" },
  { code: "K85.9", name: "Pankreatitis akut, tidak spesifik" },
  { code: "K92.0", name: "Hematemesis" },
  { code: "K92.1", name: "Melena" },

  // L — Kulit
  { code: "L01.0", name: "Impetigo akibat Staphylococcus aureus" },
  { code: "L02.9", name: "Abses kulit, furunkel dan karbunkel, tidak spesifik" },
  { code: "L03.0", name: "Selulitis jari tangan dan kaki" },
  { code: "L03.9", name: "Selulitis, tidak spesifik" },
  { code: "L20.9", name: "Dermatitis atopik, tidak spesifik (Eksem)" },
  { code: "L23.9", name: "Dermatitis kontak alergik, tidak spesifik" },
  { code: "L24.9", name: "Dermatitis kontak iritan, tidak spesifik" },
  { code: "L30.9", name: "Dermatitis, tidak spesifik" },
  { code: "L40.0", name: "Psoriasis vulgaris" },
  { code: "L50.0", name: "Urtikaria alergik" },
  { code: "L50.9", name: "Urtikaria, tidak spesifik" },
  { code: "L70.0", name: "Acne vulgaris" },

  // M — Muskuloskeletal
  { code: "M06.9", name: "Artritis reumatoid, tidak spesifik" },
  { code: "M10.0", name: "Gout idiopatik" },
  { code: "M10.9", name: "Gout, tidak spesifik" },
  { code: "M17.9", name: "Gonarthrosis (OA lutut), tidak spesifik" },
  { code: "M19.9", name: "Artritis, tidak spesifik" },
  { code: "M25.5", name: "Nyeri sendi" },
  { code: "M47.8", name: "Spondilosis lainnya" },
  { code: "M50.1", name: "Gangguan diskus servikal dengan radikulopati" },
  { code: "M51.1", name: "Gangguan diskus lumbar dengan radikulopati" },
  { code: "M54.4", name: "Lumbago dengan sciatica" },
  { code: "M54.5", name: "Nyeri punggung bawah (Low Back Pain)" },
  { code: "M75.1", name: "Sindrom manset rotator (Rotator cuff syndrome)" },
  { code: "M77.1", name: "Epikondilitis lateral (Tennis elbow)" },
  { code: "M79.1", name: "Mialgia" },
  { code: "M79.2", name: "Neuralgia dan neuritis, tidak spesifik" },
  { code: "M80.9", name: "Osteoporosis dengan fraktur patologis" },
  { code: "M81.0", name: "Osteoporosis pascamenopause" },

  // N — Genitourinari
  { code: "N10",   name: "Pielonefritis tubulointerstisial akut" },
  { code: "N17.9", name: "Gagal ginjal akut, tidak spesifik (AKI)" },
  { code: "N18.3", name: "Penyakit ginjal kronik tahap 3 (CKD 3)" },
  { code: "N18.9", name: "Gagal ginjal kronis, tidak spesifik (CKD)" },
  { code: "N20.0", name: "Kalkulus ginjal (Batu ginjal)" },
  { code: "N20.1", name: "Kalkulus ureter (Batu ureter)" },
  { code: "N23",   name: "Kolik ginjal, tidak spesifik" },
  { code: "N30.0", name: "Sistitis akut" },
  { code: "N39.0", name: "Infeksi saluran kemih, tidak spesifik (ISK)" },
  { code: "N40.1", name: "Hiperplasia prostat jinak dengan LUTS (BPH)" },
  { code: "N73.9", name: "Penyakit radang panggul (PID), tidak spesifik" },
  { code: "N76.0", name: "Vaginitis akut" },
  { code: "N80.0", name: "Endometriosis uteri" },
  { code: "N91.2", name: "Amenore, tidak spesifik" },
  { code: "N92.0", name: "Menoragia (menstruasi banyak dan sering)" },
  { code: "N95.1", name: "Menopause dan keadaan perimenopause" },

  // O — Kehamilan
  { code: "O00.1", name: "Kehamilan tuba (Ektopik)" },
  { code: "O03.9", name: "Abortus spontan, tidak spesifik" },
  { code: "O13",   name: "Hipertensi gestasional" },
  { code: "O14.1", name: "Preeklamsia berat" },
  { code: "O15.0", name: "Eklamsia dalam kehamilan" },
  { code: "O20.0", name: "Ancaman abortus" },
  { code: "O24.4", name: "Diabetes melitus gestasional (GDM)" },
  { code: "O42.9", name: "Ketuban pecah dini, tidak spesifik (KPD)" },
  { code: "O60.1", name: "Persalinan preterm" },
  { code: "O80",   name: "Persalinan normal" },
  { code: "O82.0", name: "Kelahiran melalui seksio sesarea" },

  // R — Gejala umum
  { code: "R05",   name: "Batuk" },
  { code: "R06.0", name: "Dispnea (Sesak napas)" },
  { code: "R06.2", name: "Mengi (Wheezing)" },
  { code: "R07.0", name: "Nyeri tenggorokan" },
  { code: "R07.4", name: "Nyeri dada, tidak spesifik" },
  { code: "R10.0", name: "Nyeri perut akut" },
  { code: "R10.4", name: "Nyeri perut lainnya dan tidak spesifik" },
  { code: "R11.0", name: "Mual" },
  { code: "R11.1", name: "Muntah" },
  { code: "R11.2", name: "Mual dengan muntah" },
  { code: "R12",   name: "Heartburn" },
  { code: "R17",   name: "Ikterus, tidak spesifik" },
  { code: "R19.7", name: "Diare" },
  { code: "R42",   name: "Pusing (Dizziness/Vertigo)" },
  { code: "R50.9", name: "Demam, tidak spesifik" },
  { code: "R51",   name: "Sakit kepala (Cephalgia)" },
  { code: "R52",   name: "Nyeri, tidak terklasifikasi" },
  { code: "R53",   name: "Kelemahan dan kelelahan" },
  { code: "R55",   name: "Pingsan (Sinkop)" },
  { code: "R56.0", name: "Kejang demam" },
  { code: "R56.9", name: "Kejang, tidak spesifik" },
  { code: "R60.9", name: "Edema, tidak spesifik" },
  { code: "R73.0", name: "Hiperglikemia (glukosa darah tinggi)" },

  // S & T — Cedera
  { code: "S09.9", name: "Cedera kepala, tidak spesifik" },
  { code: "S20.2", name: "Kontusio toraks" },
  { code: "S30.0", name: "Kontusio punggung bawah dan pelvis" },
  { code: "S60.0", name: "Kontusio jari tangan tanpa kerusakan kuku" },
  { code: "T14.0", name: "Luka superfisial, bagian tubuh tidak spesifik" },
  { code: "T14.1", name: "Luka terbuka, bagian tubuh tidak spesifik" },
  { code: "T30.0", name: "Luka bakar derajat I, tidak spesifik" },
  { code: "T30.1", name: "Luka bakar derajat II, tidak spesifik" },
  { code: "T78.0", name: "Syok anafilaktik akibat makanan" },
  { code: "T78.4", name: "Alergi, tidak spesifik" },

  // U — COVID-19
  { code: "U07.1", name: "COVID-19, virus teridentifikasi" },
  { code: "U07.2", name: "COVID-19, virus tidak teridentifikasi" },

  // Z — Kontak kesehatan
  { code: "Z00.0", name: "Pemeriksaan umum medis (Medical check-up)" },
  { code: "Z00.1", name: "Pemeriksaan rutin kesehatan anak" },
  { code: "Z34.0", name: "Pengawasan kehamilan normal" },
  { code: "Z39.0", name: "Perawatan dan pemeriksaan segera setelah persalinan" },
  { code: "Z76.2", name: "Pengawasan bayi sehat" },
]

/** Daftar tindakan medis ICD-9-CM dari e-klaim. */
export const icdProcedures: IcdProcedureItem[] = icd9cmEklaimProcedures
